### ISSUE TITLE
Spectrum annotator down

### ISSUE THREAD

**Issue by ludsinn** [Rappsilber-Laboratory/xiSPEC_spectrumViewer#55]
Hey,

I hope this is the right section to mention this. Faced issue indicated above when accessing 

Cheers

**Comment by colin-combe** [comment]
ok, checking whats wrong...

**Comment by colin-combe** [comment]
it works if you choose a match with no modifications in the peptides, e.g. scan 25849 in search 14391.

So its running but I guess its lost its connection to the database, so fails when looking up modification info
